import { z } from 'zod';

export const createBikeValidationSchema = z.object({
  name: z.string(),
  description: z.string(),
  pricePerHour: z.number(),
  isAvailable: z.boolean().default(true),
  cc: z.number(),
  year: z.number(),
  model: z.string(),
  brand: z.string(),
  ageGroup: z.string().array(),
  brakeType: z.string(),
  color: z.string(),
  images: z.string().array(),
  gearCount: z.number(),
  material: z.string(),
  rentalRate: z.number().optional(),
  size: z.string(),
  suspension: z.string(),
  type: z.string(),
  weight: z.number(),
});

export const updateBikeValidationSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  pricePerHour: z.number().optional(),
  isAvailable: z.boolean().default(true).optional(),
  cc: z.number().optional(),
  year: z.number().optional(),
  model: z.string().optional(),
  brand: z.string().optional(),
  ageGroup: z.string().array().optional(),
  brakeType: z.string().optional(),
  color: z.string().optional(),
  images: z.string().array().optional(),
  gearCount: z.number().optional(),
  material: z.string().optional(),
  rentalRate: z.number().optional(),
  size: z.string().optional(),
  suspension: z.string().optional(),
  type: z.string().optional(),
  weight: z.number().optional(),
});
